# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb1cae869a1034c2bfad4ef1d2d89edf71e3de5b2141fb4069cd257bdd15fc93c2c67bf7fa9551d82172775a2f26c33757ee839bf1a1e1adbff03605f5a0686a

test:
  secret_key_base: aa2c6729a957cfcecc42f11cc1018266762b9e68ec0d718581f934eebe6392ddc01b36828f8f31c53f1ab71ea8a30f0b1af7ea23e21e1f15be1b06dd3b6bace3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
